### ISSUE TITLE
This instance type `S4.SMALL1` is not available in the current zone `800007`.

### ISSUE THREAD

**Issue by yaunsky** [HXSecurity/TerraformGoat#101]
师傅您好，在构建腾讯云ssrf时，报如下错误：Error: [TencentCloudSDKError] Code=ResourceUnavailable.InstanceType, Message=This instance type `S4.SMALL1` is not available in the current zone `800007`., RequestId=77801cde-d90e-4efc-a1e5-0a0e75a38f99。查阅官方文档后，更换了实例类型，将所需类型直接写到了main.tf中，还是无法创建。不知这是什么原因呢？

**Comment by teamssix** [comment]
感谢反馈，现已和当前腾讯 CVM 所支持的实例类型同步。
